app:
  symbol: BTCUSDT
  intervals: [ "1m", "5m", "15m", "1h" ]
  barsBuffer: 300
  historyLoad: 100

binance:
  restBase: https://testnet.binancefuture.com
  wsStreamBase: wss://fstream.binancefuture.com
  recvWindowMs: 5000

spring:
  main:
    banner-mode: "off"
